# Site settings
title: Richard Hartmann blog
email: 
description: "Musings on anything"
baseurl: ""
url: "http://rihartma.github.io"
github_username:  rihartma

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: mathjax
